In [1]:
#importing libraries dataset
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.neighbors import KNeighborsRegressor
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import mean_squared_error
from sklearn.metrics import accuracy_score

import warnings as wr
wr.filterwarnings('ignore')

# 1. Import data set
df = pd.read_csv('weight-height.csv')
df.replace(to_replace=["Male", "Female"], value=[1,0], inplace=True) #male=1 ' female=0'
# df.info()
# df.Gender.value_counts()

# Step 01 - Regression

In [2]:
# 2. Separate x(Gender, Height) and y (y=Weight)
# x = df.iloc[:,[0,1]]
# y = df.iloc[:,[-1]]
x = df.drop('Weight', axis=1)
y = df[['Weight']]

#3. Train = 70%, Test = 30%from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, train_size=.3, random_state=10)

# 4. Apply Linear Regression
lr=LinearRegression()
lr.fit(x_train,y_train)
y_pred = lr.predict(x_test)
print(y_pred)

[[175.28559048]
 [125.97807182]
 [198.09213057]
 ...
 [ 90.61939845]
 [192.26926764]
 [208.77244495]]


In [3]:
# 5. Evaluate the Model (Testing and training Accuracy, MSE for testing)
mse = mean_squared_error(y_test, y_pred)
tta = lr.score(x_test, y_test)
print(f"Mse in linear linear reg: {mse}")
print(f"Testing and training Accuracy in linear reg: {tta}")

Mse in linear linear reg: 102.53560862214007
Testing and training Accuracy in linear reg: 0.9000576996572582


In [4]:
# 6. Apply KNN Regressor: https://scikit-learn.org/stable/modules/generated/sklearn.neighbors.KNeighborsRegressor.html
kl=KNeighborsRegressor()
kl.fit(x_train, y_train)
y_pred= kl.predict(x_test)
print(y_pred)


[[181.46533094]
 [130.00128478]
 [200.19309534]
 ...
 [ 93.56032375]
 [196.97655418]
 [213.6928609 ]]


In [5]:
# 7. Evaluate the Model (Testing and training Accuracy, MSE for testing)
mse = mean_squared_error(y_test, y_pred)
tta = kl.score(x_test, y_test)
print(f"Mse in knn reg: {mse}")
print(f"Testing and training Accuracy in knn reg :{tta}")

Mse in knn reg: 122.99581877497853
Testing and training Accuracy in knn reg :0.8801149646830488


# Step 02 - Classification

In [6]:
#df.replace(to_replace=["Male", "Female"], value=[1,0], inplace=True) #male=1 ' female=0'

#2. Separate x and (y=Gender)
# x = df.iloc[:, [1,2]]
# y = df.iloc[:, [0]]
x = df.drop('Gender', axis=1)
y = df[['Gender']]

# 3. Train = 70%, Test = 30%
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=.30, random_state=10)

#4. Apply KNN Classifier
kc = KNeighborsClassifier(n_neighbors=100)

# Fit the classifier to the training data
kc.fit(x_train, y_train)

KNeighborsClassifier(n_neighbors=100)

In [7]:
# Predict the classes of the testing data
y_pred = kc.predict(x_test) # 1 = male ; 0 = female
print(y_pred)

[1 0 1 ... 1 1 1]


In [8]:
# 5. Evaluate the Model by only Accuracy.
accuracy = accuracy_score(y_test, y_pred )
print(f"Accuracy in knn classifier: {accuracy}")

Accuracy in knn classifier: 0.9232567199065056
